import json
from pathlib import Path
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
TO_APPLY_PATH = ROOT / "data" / "to_apply.json"
TAILORED_DIR = ROOT / "tailored"

def assist_with_application():
    if not TO_APPLY_PATH.exists():
        print(f"⚠️ Error: {TO_APPLY_PATH} not found. Please run filter_jobs.py first.")
        return

    with open(TO_APPLY_PATH, "r", encoding="utf-8") as f:
        jobs = json.load(f)

    # Find the first job that has documents drafted but hasn't been applied to yet
    job_to_apply = None
    for job in jobs:
        if job.get('documents_drafted') and not job.get('applied'):
            job_to_apply = job
            break

    if not job_to_apply:
        print("🎉 No jobs found awaiting application. You are all caught up!")
        return

    print(f"\n{'='*50}")
    print(f"🚀 PREPARING APPLICATION: {job_to_apply.get('title')} at {job_to_apply.get('company')}")
    print(f"{'='*50}")

    # Pull the exact document paths generated by the Qwen3:8b model
    cv_path = job_to_apply.get('cv_path', 'Not generated')
    cl_path = job_to_apply.get('cl_path', 'Not generated')

    print(f"\n🔗 Target URL: {job_to_apply.get('url')}")
    print(f"📄 Tailored CV Path: {cv_path}")
    print(f"📄 Tailored CL Path: {cl_path}")
    print("\n*(Note: Your AI generated these as Markdown. Ensure you export them to PDF if the portal requires it!)*")
    
    print("\nHooking into your Native Chrome Session on port 9222...")
    
    try:
        with sync_playwright() as p:
            # Reusing the CDP Hijack to bypass application portal firewalls (like Greenhouse/Lever)
            browser = p.chromium.connect_over_cdp("http://localhost:9222")
            context = browser.contexts[0]
            page = context.new_page()
            
            page.goto(job_to_apply.get('url', ''))
            
            # Wait for your explicit command in the terminal
            while True:
                user_input = input("\n> Type 'ok' and press Enter when you have submitted the application (or 'skip' to skip): ").strip().lower()
                
                if user_input == 'ok':
                    job_to_apply['applied'] = True
                    print(f"✅ Marked '{job_to_apply.get('title')}' as applied in the JSON database!")
                    break
                elif user_input == 'skip':
                    print("⏭️ Skipping this application for now. It will remain in your queue.")
                    break
                else:
                    print("Invalid command. Please type 'ok' or 'skip'.")
            
            page.close()
            
    except Exception as e:
        print(f"\n❌ CDP Error: Could not connect to Chrome.")
        print("Make sure you launched your native Chrome window with: chrome.exe --remote-debugging-port=9222")
        print(f"Details: {e}")
        return

    # Save the updated status back to the JSON file so we don't apply twice
    with open(TO_APPLY_PATH, "w", encoding="utf-8") as f:
        json.dump(jobs, f, indent=4, ensure_ascii=False)

if __name__ == "__main__":
    assist_with_application()